services:

  rosbot:
    image: husarion/rosbot:humble
    network_mode: host
    ipc: host
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: ros2 launch rosbot_bringup rosbot_bringup.launch.py
  
  microros:
    image: husarion/micro-ros-agent:humble
    network_mode: host
    ipc: host
    devices:
      - ${SERIAL_PORT:?err}
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    command: ros2 run micro_ros_agent micro_ros_agent serial -D $SERIAL_PORT serial -b 576000 # -v6

  rplidar:
    image: husarion/rplidar:humble
    network_mode: host
    ipc: host
    devices:
      - ${LIDAR_SERIAL:?err}:/dev/ttyUSB0
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  mapping:
    image: husarion/slam-toolbox:humble
    network_mode: host
    ipc: host
    volumes:
      - ./config/slam_toolbox_params.yaml:/slam_params.yaml
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=False
