services:

  map-saver:
    image: husarion/nav2-map-server:humble
    network_mode: host
    ipc: host
    volumes:
      - ./maps:/maps
    env_file: net.env
    command: bash -c "while true; do ros2 run nav2_map_server map_saver_cli --free 0.15 --fmt png -f /maps/map; sleep 5; done"

  rviz:
    image: husarion/rviz2:galactic
    container_name: rviz
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    env_file: net.env
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1

  joy2twist:
    image: husarion/joy2twist:humble
    network_mode: host
    ipc: host
    devices:
      - /dev/input
    volumes:
      - ./config/joy2twist.yaml:/joy2twist.yaml
    env_file: net.env
    command: >
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml
