services:

  rosbot:
    image: husarion/rosbot:humble-nightly
    network_mode: host
    ipc: host
    env_file: ${NET_CONFIG_FILE:-.env.lan}
    environment:
      - RMW_IMPLEMENTATION
    command: ros2 launch rosbot_bringup bringup.launch.py
  
  microros:
    image: husarion/micro-ros-agent:humble-nightly
    network_mode: host
    ipc: host
    devices:
      - ${SERIAL_PORT:?err}
    env_file: ${NET_CONFIG_FILE:-.env.lan}
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    command: ros2 run micro_ros_agent micro_ros_agent serial -D $SERIAL_PORT serial -b 576000 # -v6

  rplidar:
    image: husarion/rplidar:humble-nightly
    network_mode: host
    ipc: host
    devices:
      - ${LIDAR_SERIAL:?err}:/dev/ttyUSB0
    env_file: ${NET_CONFIG_FILE:-.env.lan}
    environment:
      - RMW_IMPLEMENTATION
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  mapping:
    image: husarion/slam-toolbox:humble-nightly
    network_mode: host
    ipc: host
    volumes:
      - ./config/slam_toolbox_params.yaml:/slam_params.yaml
    env_file: ${NET_CONFIG_FILE:-.env.lan}
    environment:
      - RMW_IMPLEMENTATION
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=False
