x-dds-configs:
  - &client_config { network_mode: host, ipc: host, configs: [ client.xml ], env_file: dds/client.env }
  - &server_config { network_mode: host, ipc: host, configs: [ server.xml ], env_file: dds/server.env }
  - &simple_config { network_mode: host, ipc: host, configs: [ simple.xml ], env_file: dds/simple.env }

configs: 
  client.xml: { file: dds/client.xml }
  server.xml: { file: dds/server.xml }
  simple.xml: { file: dds/simple.xml }

services:

  rviz:
    <<: *simple_config
    image: husarion/rviz2:humble-22-11-17
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1

  joy2twist:
    <<: *simple_config
    image: husarion/joy2twist:humble-22-11-17
    devices:
      - /dev/input
    volumes: 
      - ./config/joy2twist.yaml:/joy2twist.yaml
    command: > 
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml

  mapping:
    <<: *simple_config
    image: husarion/slam-toolbox:humble-22-11-17
    container_name: slam-toolbox
    volumes:
      - ./config/slam_toolbox_params.yaml:/slam_params.yaml
      - ./maps:/maps
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}