services:

  map-saver:
    # image: husarion/nav2-map-server:humble
    build: { args: [ IMAGE=husarion/nav2-map-server:humble ] }
    network_mode: host
    ipc: host
    volumes:
      - ./maps:/maps
    environment:
      - RMW_IMPLEMENTATION
      - CYCLONEDDS_URI
      - FASTRTPS_DEFAULT_PROFILES_FILE
      - ROS_DISCOVERY_SERVER
    command: bash -c "while true; do ros2 run nav2_map_server map_saver_cli --free 0.15 --fmt png -f /maps/map; sleep 5; done"

  rviz:
    # image: husarion/rviz2:humble
    build: { args: [ IMAGE=husarion/rviz2:humble ] }
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    environment:
      - RMW_IMPLEMENTATION
      - CYCLONEDDS_URI
      - FASTRTPS_DEFAULT_PROFILES_FILE
      - ROS_DISCOVERY_SERVER
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1

  joy2twist:
    # image: husarion/joy2twist:humble
    build: { args: [ IMAGE=husarion/joy2twist:humble ] }
    network_mode: host
    ipc: host
    devices:
      - /dev/input
    volumes:
      - ./config/joy2twist.yaml:/joy2twist.yaml
    environment:
      - RMW_IMPLEMENTATION
      - CYCLONEDDS_URI
      - FASTRTPS_DEFAULT_PROFILES_FILE
      - ROS_DISCOVERY_SERVER
    command: >
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml