services:

  ds:
    # image: husarion/rosbot:humble
    build: { args: [ IMAGE=husarion/rosbot:humble ] }
    network_mode: host
    ipc: host
    environment:
      - DISCOVERY_SERVER_PORT
    command: fast-discovery-server -x /var/tmp/husarnet-dds/fastdds-ds-server.xml

  rosbot:
    # image: husarion/rosbot:humble
    build: { args: [ IMAGE=husarion/rosbot:humble ] }
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION
      - FASTRTPS_DEFAULT_PROFILES_FILE
      - CYCLONEDDS_URI
      - ROS_DISCOVERY_SERVER
    command: ros2 launch rosbot_bringup rosbot_bringup.launch.py
  
  microros:
    # image: husarion/micro-ros-agent:humble
    build: { args: [ IMAGE=husarion/micro-ros-agent:humble ] }
    network_mode: host
    ipc: host
    devices:
      - ${SERIAL_PORT:?err}
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=${FASTRTPS_DEFAULT_PROFILES_FILE:-/fastdds.xml}
      - ROS_DISCOVERY_SERVER
    command: ros2 run micro_ros_agent micro_ros_agent serial -D $SERIAL_PORT serial -b 576000 # -v6

  rplidar:
    # image: husarion/rplidar:humble
    build: { args: [ IMAGE=husarion/rplidar:humble ] }
    network_mode: host
    ipc: host
    devices:
      - ${LIDAR_SERIAL:?err}:/dev/ttyUSB0
    environment:
      - RMW_IMPLEMENTATION
      - CYCLONEDDS_URI
      - FASTRTPS_DEFAULT_PROFILES_FILE
      - ROS_DISCOVERY_SERVER
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  mapping:
    # image: husarion/slam-toolbox:humble
    build: { args: [ IMAGE=husarion/slam-toolbox:humble ] }
    network_mode: host
    ipc: host
    volumes:
      - ./config/slam_toolbox_params.yaml:/slam_params.yaml
    environment:
      - RMW_IMPLEMENTATION
      - CYCLONEDDS_URI
      - FASTRTPS_DEFAULT_PROFILES_FILE
      - ROS_DISCOVERY_SERVER
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=False
