x-net-config: &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:

  rosbot:
    image: husarion/rosbot:humble-0.6.1-20230712
    <<: *net-config
    command: ros2 launch rosbot_bringup bringup.launch.py
  
  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    <<: *net-config
    devices:
      - ${SERIAL_PORT:?err}
    command: MicroXRCEAgent serial -D $SERIAL_PORT serial -b 576000

  rplidar:
    image: husarion/rplidar:humble
    <<: *net-config
    devices:
      - ${LIDAR_SERIAL:?err}:/dev/ttyUSB0
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}
  
  mapping:
    image: husarion/slam-toolbox:humble
    <<: *net-config
    volumes:
      - ./config/slam_toolbox.yaml:/slam_params.yaml
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=False
